"""
    NFT Storage API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nft_storage
from nft_storage.model.check_response_value import CheckResponseValue
globals()['CheckResponseValue'] = CheckResponseValue
from nft_storage.model.check_response import CheckResponse


class TestCheckResponse(unittest.TestCase):
    """CheckResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCheckResponse(self):
        """Test CheckResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CheckResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
