"""
    NFT Storage API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import nft_storage
from nft_storage.api.nft_storage_api import NFTStorageAPI  # noqa: E501


class TestNFTStorageAPI(unittest.TestCase):
    """NFTStorageAPI unit test stubs"""

    def setUp(self):
        self.api = NFTStorageAPI()  # noqa: E501

    def tearDown(self):
        pass

    def test_check(self):
        """Test case for check

        Check if a CID of an NFT is being stored by nft.storage.  # noqa: E501
        """
        pass

    def test_delete(self):
        """Test case for delete

        Stop storing the content with the passed CID  # noqa: E501
        """
        pass

    def test_list(self):
        """Test case for list

        List all stored files  # noqa: E501
        """
        pass

    def test_status(self):
        """Test case for status

        Get information for the stored file CID  # noqa: E501
        """
        pass

    def test_store(self):
        """Test case for store

        Store a file  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
