"""
    NFT Storage API

    # API Reference   # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nft_storage
from nft_storage.model.deal import Deal
globals()['Deal'] = Deal
from nft_storage.model.nft_deals import NFTDeals


class TestNFTDeals(unittest.TestCase):
    """NFTDeals unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNFTDeals(self):
        """Test NFTDeals"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NFTDeals()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
