"""
    NFT Storage API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nft_storage
from nft_storage.model.files import Files


class TestFiles(unittest.TestCase):
    """Files unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFiles(self):
        """Test Files"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Files()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
