"""
    NFT Storage API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nft_storage
from nft_storage.model.delete_response import DeleteResponse


class TestDeleteResponse(unittest.TestCase):
    """DeleteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteResponse(self):
        """Test DeleteResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeleteResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
