# flake8: noqa

"""
    NFT Storage API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from nft_storage.api_client import ApiClient

# import Configuration
from nft_storage.configuration import Configuration

# import exceptions
from nft_storage.exceptions import OpenApiException
from nft_storage.exceptions import ApiAttributeError
from nft_storage.exceptions import ApiTypeError
from nft_storage.exceptions import ApiValueError
from nft_storage.exceptions import ApiKeyError
from nft_storage.exceptions import ApiException
